apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2hhcmJvci5ocGUuY2hhcml0eS1wcm9qZWN0LmV1Ijp7InVzZXJuYW1lIjoiaGFyYm9yX3VzZXIxIiwicGFzc3dvcmQiOiI3eU9GYk5QVHppWUpJdDhjTnBDRjJTNWZqSVJGWDI0WSIsImF1dGgiOiJhR0Z5WW05eVgzVnpaWEl4T2pkNVQwWmlUbEJVZW1sWlNrbDBPR05PY0VOR01sTTFabXBKVWtaWU1qUloifX19
kind: Secret
metadata:
  name: harbor-secret
  namespace: {{ namespace }}
type: kubernetes.io/dockerconfigjson