apiVersion: v1
kind: Service
metadata:
  name: {{svc_name}}
  namespace: {{namespace}}
  {% if is_public %}
  {% if exp.protocol == 'UDP' or exp.protocol == 'TCP' %}
  annotations:  
    metallb.universe.tf/address-pool: public-pool
    metallb.universe.tf/allow-shared-ip: liqo-shared
  {% endif %}
  {% endif %}
  labels:
    app: {{name}}
    service: {{svc_name}}
spec:
  ports:
  - port: {{ exp.clusterPort }}
    name: {{ exp.name.lower() }}
    {% if exp.protocol == 'HTTP' %}
    protocol: TCP
    {% else %}
    protocol: {{ exp.protocol }}

    {% endif %}
    targetPort: {{ exp.containerPort }}
  selector:
    app: {{name}}
  {% if is_public %}
  {% if exp.protocol == 'UDP' or exp.protocol == 'TCP' %}
  type: LoadBalancer
  {% endif %}
  {% endif %}
