apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - image: eclipse-mosquitto:latest
        name: mqtt-broker
        ports:
        - containerPort: 1883
          name: mqtt
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mqtt-config-volume
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mqtt-config-volume
        configMap:
          name: mqtt-config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seLinuxOptions:
          level: s0:c123,c456
        supplementalGroups:
          - 1000
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
  selector:
    app: mqtt-broker
