apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.16.1/32
  - 172.16.16.3/32
  - 172.16.16.4/32
  - 172.16.16.5/32
  - 172.16.16.6/32
  - 172.16.16.7/32
  - 172.16.16.8/32
  - 172.16.16.9/32
  - 172.16.16.10/32
  - 172.16.16.11/32
  - 172.16.16.12/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses: x.x.x.x/y
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: all-pools
  namespace: metallb-system